#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#gem install soulmate

bundle install

wget http://redis.googlecode.com/files/redis-2.4.15.tar.gz
tar xzf redis-2.4.15.tar.gz
rm -rf redis-2.4.15.tar.gz
cd redis-2.4.15
make

src/redis-server &

cd ..

soulmate load standard --redis=redis://localhost:6379/0 < soulmate_import.json

cp soulmate-0.1.3 -r ~/.rvm/gems/ruby-1.9.3-p194/gems/

echo ""
echo "Install completed! Restart the Rails server to apply the gem changes."
echo "To execute a search on 'cat': http://localhost:3000/sm/search?types[]=standard&term=cat"

exit 1
