#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

apt-get install openjdk-7-jre-headless -y

curl -k -L -o elasticsearch-0.19.0.tar.gz http://github.com/downloads/elasticsearch/elasticsearch/elasticsearch-0.19.0.tar.gz
tar -zxvf elasticsearch-0.19.0.tar.gz
mkdir /usr/local/share/elasticsearch/
mv elasticsearch-0.19.0/* /usr/local/share/elasticsearch
rm -rf elasticsearch-*
echo "elasticsearch installed to /usr/local/share/elasticsearch/bin/elasticsearch\n" 1>&2
exit 1
