#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

cp soulmate-0.1.3 -r ~/.rvm/gems/ruby-1.9.3-p194/gems/

if [ "$?" -ne "0" ]; then
	cp soulmate-0.1.3 -r ~/.rvm/gems/ruby-1.9.2-p318/gems/
fi

exit 1
